# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relaxation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('isHot', models.BooleanField()),
                ('time', models.TimeField(default=datetime.time(12, 0))),
                ('places', models.PositiveIntegerField()),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Excursion')),
                ('relaxation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Relaxation')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Shopping')),
            ],
        ),
    ]
